apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rooster-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rooster-nodejs 
  name: rooster-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rooster-nodejs 
